require('base')
require('plugins')
require('keymaps')
require('colorscheme')
require('neovide')
require('plugins.comment')
require('plugins.nvim-cmp')
require('lsp')
require('plugins.gitsigns')
require('plugins.nvim-tree')
require('plugins.lualine')
require('plugins.nvim-treesitter')
require('plugins.nvim-telescope')
require('plugins.nvim-autopairs')
require('plugins.nvim-leap')
require('plugins.neogen')
-- require('plugins.lint')
require('plugins.toggleterm')
require('plugins.dashboard')
require('plugins.nvim-surround')
-- require('plugins.dap')
